### ISSUE TITLE
Current Project Status

### ISSUE THREAD

**Issue by JanMalte** [django-crispy-forms/crispy-bootstrap5#145]
Hi,

there are quite some highly requested issues and even merge requests waiting to be merged for quite some time now.

There hasn't been any new feature release or even bugfix release since february.

Is there any need for additional maintainers to push the project forward?

Best regards,
Malte

**Comment by smithdc1** [comment]
Hey @JanMalte  -- Yes, both fresh PRs and reviews of existing ones are always very welcome!

If you'd like to update any of the PRs so that the tests pass (and ensure that any patches have tests) that would be wonderful. 🎁 

I've also started to update versions of dependencies and so on in https://github.com/django-crispy-forms/crispy-bootstrap5/pull/146.
