### ISSUE TITLE
Improve select: missing "arrow down"

### ISSUE THREAD

**Issue by cpina** [django-crispy-forms/crispy-bootstrap5#22]
Using `crispy-bootstrap5` a `<select>` is generated like this:
```
<select name="person_form-academic_title" class="select form-control" ...
```
It renders like this (notice the missing "arrow down"):
![academic-title](https://user-images.githubusercontent.com/489071/101655151-2dbf7100-3a39-11eb-9205-c7f9bb2306c8.png)

If it did `class="form-select"`as per https://getbootstrap.com/docs/5.0/forms/select/ it would look like:
![select-bootstrap5](https://user-images.githubusercontent.com/489071/101655338-68c1a480-3a39-11eb-8141-33e9bff7246e.png)

Side note: on Bootstrap5 will look nicer than what we have using Bootstrap4:
![select-bootstrap4](https://user-images.githubusercontent.com/489071/101655485-9575bc00-3a39-11eb-9077-e74166d3f68a.png)

**Comment by cpina** [comment]
Actually we have the same problem on Bootstrap4 (I'm really surprised!). I think that we should use `class="custom-select"` in django-crispy-forms for the `select`. Tomorrow I'll have another look, probably a PR on django-crispy-forms and in crispy-bootstrap5 (the class name has changed I think).

**Comment by cpina** [comment]
When we finish the related fix for Bootstrap4 I'll apply the fix in Bootstrap5.

**Comment by smithdc1** [comment]
Fixed in https://github.com/django-crispy-forms/crispy-bootstrap5/commit/f0fc8170f9c0604d949f20b3fd4da39d024dc27b

I applied the same sort of logic as we did for bootstrap4. I wanted to do this as selects were currently completely broken (no arrow at all!). So feel like the simple fix is a nice improvement to get out there. 

We can come back and look at refactoring this to reduce the repetitive nature in due course.
