### ISSUE TITLE
Default mb-3 in field.html may cause problems

### ISSUE THREAD

**Issue by AndyAnderson91** [django-crispy-forms/crispy-bootstrap5#74]
I'm talking about default behavior of creating div with class='mb-3' on every form field, which is convenient in many cases, but in my case it was a huge problem, since my form was in navbar, and i simple didnt need so big interval to bottom border. I haven't found acceptable solution (one idea i had is to overwrite field.html file and i decided to avoid it), and that leaded me to style this form without crispy. Everything else is great by the way.

**Comment by smithdc1** [comment]
Thanks for the comment

> which is convenient in many cases,

I think this is what we have to aim for. That is, let's try and provide something that works for the most common use cases. 

If you need something more custom then I think your always going to need something more bespoke, be it over riding a crispy template or in your own template. Happy to hear views on what else we could do here as I'm not sure. 🤔

**Comment by cbracco** [comment]
@smithdc1 would be great if we could open this one up for conversation again. Would be great to be able to configure this spacing class globally and/or per-field somehow.

**Comment by smithdc1** [comment]
Thanks for the feedback 👍 

Do you have any concrete thoughts on how this could be implemented?

**Comment by cbracco** [comment]
Simplest thing would be to just add back some generic class like `form-group` or similar that could be targeted for layout-type styling like space between form fields, instead of relying on utility classes since use cases for them will vary widely. 

I realize using margin utility classes is the suggested implementation from Bootstrap but its an ill-advised one in my view. I technically could use the Bootstrap utility API to make `.mb-3` mean something else entirely if I wanted to. In our case, we use a set of spacer values that is different from Bootstrap’s built-in set, so for us `mb-3` maps to a different value. It’d be much easier for us to add and maintain a few lines of CSS applied to a generic class like `.form-group` to give fields some sensible base styles, and call it a day (this is what were doing in a forked version at the moment).

Open to configuration ideas too but nothing immediate comes to mind at the moment. I can do some more intentional thinking about this and report back, though. Would be great to get ideas from others as well.

**Comment by smithdc1** [comment]
> add back some generic class like form-group or similar

These classes were all dropped in bootstrap-5, see [docs](https://getbootstrap.com/docs/5.0/migration/#forms) and as you say their recommendation is to replace it with `mb-3` and is what they use in their [examples](https://getbootstrap.com/docs/5.0/forms/form-control/).

For the standard case I think we need to use these classes but maybe we need an escape hatch here. 

One thought would be to override it with `wrapper_class`. We could do something like `{% if wrapper_class %} {{ wrapper_class }}{% else %} mb-3{% endif %}` Folk could then add their own classes, but I guess you couldn't just use `None`...

> .mb-3 mean something else entirely if I wanted to

There's some limit to what the template pack can do, yes you can make customisation but we a generalised template pack won't be able to accommodate that.
