### ISSUE TITLE
the tags are escaped in the label

### ISSUE THREAD

**Issue by scwall** [django-crispy-forms/crispy-bootstrap5#87]
Hello,
It seems that the fields are escaped in the label when we add tags with crispy-bootstrap5 I do not have the problem with crispy bootstrap4
example:

escaped in template 5
`forms.CheckboxInput(attrs={'class': 'form-check-input'}),label= f"{_('I have read and agree to the')} <a href=\"#\">...}`
![image](https://user-images.githubusercontent.com/30811539/145711118-52ef546d-53c4-4eac-aa90-a5fd2c143b57.png)

no escaped in template 4
![image](https://user-images.githubusercontent.com/30811539/145711142-a56519e3-9a3a-4827-b78e-5adf3b5a11fe.png)

**Comment by smithdc1** [comment]
We have an open issue on the existing template packs that we use `|safe` too frequently and that is unsafe. As we're starting afresh with the Bootstrap5 template pack we've taken the opportunity to start remove these. 

The fix is that you'll need to wrap your string label in [SafeString](https://docs.djangoproject.com/en/3.2/ref/utils/#module-django.utils.safestring) and thereby explicitly marking this as safe.

**Comment by smithdc1** [comment]
p.s. embedding a link in a label isn't considered best practice. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#interactive_content

**Comment by scwall** [comment]
Perfect thank you very much for your answer, indeed I will look to adapt this in my code
